-- 插入初始用户数据
INSERT INTO hib_user (username, email, password, avatar_url, status, theme_dark, email_notifications, language, bio)
VALUES ('Cow-50482dbc41',
        '2148582258@qq.com',
        'default_password', -- 在这里设置一个默认的密码，假设这是一个初级用户数据
        'https://cetide-1325039295.cos.ap-chengdu.myqcloud.com/west/default_user.png',
        'ACTIVE',
        0,
        1,
        'zh-CN',
        '此用户很懒, 什么也没有留下.....');

INSERT INTO hib_plugins (plugin_name, plugin_type, version, webhook_url, api_url, documentation_url, author, created_at,
                         updated_at, deleted)
VALUES ('支付网关', '支付', '1.0.0', 'https://example.com/webhook/payment', 'https://example.com/api/payment',
        'https://example.com/docs/payment', '张三', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('分析追踪器', '分析', '2.1.0', 'https://example.com/webhook/analytics', 'https://example.com/api/analytics',
        'https://example.com/docs/analytics', '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('SEO优化器', 'SEO', '3.3.0', 'https://example.com/webhook/seo', 'https://example.com/api/seo',
        'https://example.com/docs/seo', '王五', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('用户管理', '认证', '1.2.1', 'https://example.com/webhook/user', 'https://example.com/api/user',
        'https://example.com/docs/user', '赵六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('邮件通知', '邮件', '1.0.0', 'https://example.com/webhook/email', 'https://example.com/api/email',
        'https://example.com/docs/email', '钱七', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('社交登录', '认证', '1.5.0', 'https://example.com/webhook/social', 'https://example.com/api/social',
        'https://example.com/docs/social', '孙八', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('文件上传', '工具', '2.0.0', 'https://example.com/webhook/upload', 'https://example.com/api/upload',
        'https://example.com/docs/upload', '周九', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('CRM 集成', 'CRM', '4.0.0', 'https://example.com/webhook/crm', 'https://example.com/api/crm',
        'https://example.com/docs/crm', '吴十', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('聊天机器人', 'AI', '3.2.1', 'https://example.com/webhook/chatbot', 'https://example.com/api/chatbot',
        'https://example.com/docs/chatbot', '郑十一', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('支付欺诈检测', '安全', '1.3.0', 'https://example.com/webhook/fraud', 'https://example.com/api/fraud',
        'https://example.com/docs/fraud', '冯十二', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('库存管理', '电商', '2.4.0', 'https://example.com/webhook/inventory', 'https://example.com/api/inventory',
        'https://example.com/docs/inventory', '陈十三', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('联盟计划', '市场营销', '1.0.0', 'https://example.com/webhook/affiliate', 'https://example.com/api/affiliate',
        'https://example.com/docs/affiliate', '杨十四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('地理位置服务', '工具', '2.3.0', 'https://example.com/webhook/geo', 'https://example.com/api/geo',
        'https://example.com/docs/geo', '朱十五', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('视频播放器', '媒体', '5.1.2', 'https://example.com/webhook/video', 'https://example.com/api/video',
        'https://example.com/docs/video', '梁十六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('安全扫描器', '安全', '1.2.1', 'https://example.com/webhook/security', 'https://example.com/api/security',
        'https://example.com/docs/security', '张十七', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('数据备份', '工具', '3.1.0', 'https://example.com/webhook/backup', 'https://example.com/api/backup',
        'https://example.com/docs/backup', '李十八', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('翻译服务', '工具', '1.0.0', 'https://example.com/webhook/translate', 'https://example.com/api/translate',
        'https://example.com/docs/translate', '王十九', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('电子签名', '电子签名', '2.0.0', 'https://example.com/webhook/signature', 'https://example.com/api/signature',
        'https://example.com/docs/signature', '赵二十', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('广告拦截器', '浏览器', '1.1.0', 'https://example.com/webhook/adblock', 'https://example.com/api/adblock',
        'https://example.com/docs/adblock', '钱二十一', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('内容管理', 'CMS', '4.5.0', 'https://example.com/webhook/cms', 'https://example.com/api/cms',
        'https://example.com/docs/cms', '孙二十二', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('云存储', '云', '3.0.0', 'https://example.com/webhook/cloud', 'https://example.com/api/cloud',
        'https://example.com/docs/cloud', '周二十三', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('实时聊天', '客户支持', '2.2.0', 'https://example.com/webhook/livechat', 'https://example.com/api/livechat',
        'https://example.com/docs/livechat', '吴二十四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('任务管理', '生产力', '1.4.0', 'https://example.com/webhook/taskmanager', 'https://example.com/api/taskmanager',
        'https://example.com/docs/taskmanager', '郑二十五', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('订阅计费', '计费', '1.1.0', 'https://example.com/webhook/billing', 'https://example.com/api/billing',
        'https://example.com/docs/billing', '冯二十六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('客户反馈', '调查', '2.0.0', 'https://example.com/webhook/feedback', 'https://example.com/api/feedback',
        'https://example.com/docs/feedback', '李二十七', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
       ('事件调度', '工具', '3.4.0', 'https://example.com/webhook/scheduler', 'https://example.com/api/scheduler',
        'https://example.com/docs/scheduler', '王二十八', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO hib_knowledge_base (id, name, description, type, owner_id, cover_url)
VALUES (1, '默认知识库', '默认的知识库', 'PRIVATE', 1, 'https://example.com/webhook/scheduler')

