CREATE TABLE hib_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(100) NOT NULL UNIQUE,
    email               VARCHAR(100) UNIQUE,
    password            VARCHAR(255) NOT NULL,
    avatar_url          VARCHAR(255),
    status              VARCHAR(50) DEFAULT 'ACTIVE',
    theme_dark          INT  DEFAULT 0,
    email_notifications INT  DEFAULT 1,
    language            VARCHAR(50) DEFAULT 'EN',
    current_organization_id BIGINT DEFAULT 0,
    bio                 TEXT,
    created_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted             INT  DEFAULT 0
);

CREATE TABLE hib_organization
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL UNIQUE,
    description     TEXT,
    owner_id        BIGINT       NOT NULL,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT  DEFAULT 0,
    status          VARCHAR(50) DEFAULT 'ACTIVE',
    published       INT  DEFAULT 0,
    max_members     INT         DEFAULT 50,
    current_members INT         DEFAULT 0
);

CREATE TABLE hib_organization_member
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    role            VARCHAR(50) DEFAULT 'MEMBER',
    status          VARCHAR(50) DEFAULT 'ACTIVE',
    joined_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT  DEFAULT 0,
    CONSTRAINT uk_org_user UNIQUE (organization_id, user_id)
);

CREATE TABLE hib_org_invite
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    inviter_id      BIGINT NOT NULL,
    invite_code     VARCHAR(100) UNIQUE,
    role            VARCHAR(50) DEFAULT 'MEMBER',
    max_uses        INT         DEFAULT 1,
    used_count      INT         DEFAULT 0,
    expires_at      TIMESTAMP,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT  DEFAULT 0
);

CREATE TABLE hib_knowledge_base
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    type            VARCHAR(50) DEFAULT 'PRIVATE',
    owner_id        BIGINT       NOT NULL,
    organization_id BIGINT,
    cover_url       VARCHAR(255),
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT  DEFAULT 0
);

CREATE TABLE hib_knowledge_base_collaborator
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT NOT NULL,
    user_id           BIGINT NOT NULL,
    role              VARCHAR(50) DEFAULT 'EDITOR',
    joined_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    created_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted           INT  DEFAULT 0,
    CONSTRAINT uk_kb_user UNIQUE (knowledge_base_id, user_id)
);

CREATE TABLE hib_document
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id  BIGINT       NOT NULL,
    parent_id          BIGINT      DEFAULT NULL,
    title              VARCHAR(255) NOT NULL,
    type               VARCHAR(50) DEFAULT 'DOC',
    owner_id           BIGINT       NOT NULL,
    sort_order         INT         DEFAULT 0,
    status             VARCHAR(50) DEFAULT 'ACTIVE',
    version            INT         DEFAULT 1,
    level              INT         DEFAULT 0,
    published          INT  DEFAULT 0,
    current_version_id BIGINT      DEFAULT NULL,
    metadata           JSON,
    created_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted            INT  DEFAULT 0
);

CREATE TABLE hib_document_comment
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    content     TEXT   NOT NULL,
    anchor      JSON,
    status      VARCHAR(50) DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted     INT  DEFAULT 0
);

CREATE TABLE hib_operation_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(100) NOT NULL,
    description TEXT,
    user_id     BIGINT,
    operator    VARCHAR(100) NOT NULL,
    success     INT      NOT NULL,
    params      TEXT,
    result      TEXT,
    timestamp   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     TINYINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP              DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP              DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hib_document_favorite
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    document_id  BIGINT NOT NULL,
    favorited_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_at   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ,
    deleted      INT DEFAULT 0,
    CONSTRAINT uk_user_doc UNIQUE (user_id, document_id)
);

CREATE TABLE hib_notification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id       BIGINT                            NOT NULL,
    type          VARCHAR(32)                       NOT NULL,
    title         VARCHAR(255)                      NOT NULL,
    content       TEXT,
    level         VARCHAR(32)                                DEFAULT 'NORMAL',
    is_read       INT                           NOT NULL DEFAULT FALSE,
    business_id   varchar(255)                               DEFAULT NULL,
    business_type VARCHAR(64)                                DEFAULT NULL,
    extra_data    JSON                                       DEFAULT NULL,
    send_time     TIMESTAMP                                   DEFAULT NULL,
    read_time     TIMESTAMP                                   DEFAULT NULL,
    deleted       TINYINT                           NOT NULL DEFAULT 0,
    created_at    TIMESTAMP                                   DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP                                   DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (id)
);

CREATE TABLE hib_tag
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    color      VARCHAR(20) DEFAULT '#CCCCCC',
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted    INT  DEFAULT 0
);

CREATE TABLE hib_entity_tag (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity_type  TINYINT NOT NULL,
    entity_id    BIGINT NOT NULL,
    tag_id       BIGINT NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted      TINYINT DEFAULT 0,
    CONSTRAINT uk_entity_tag UNIQUE (entity_type, entity_id, tag_id)
); -- H2正确的表注释语法（双引号）

-- 创建实体查询索引（按实体类型+ID查询标签）
CREATE INDEX idx_entity ON hib_entity_tag (entity_type, entity_id);
-- 创建标签查询索引（按标签ID查询关联实体）
CREATE INDEX idx_tag ON hib_entity_tag (tag_id);

CREATE TABLE hib_document_template
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    content     LONGTEXT     NOT NULL,
    creator_id  BIGINT       NOT NULL,
    scope       VARCHAR(50) DEFAULT 'PRIVATE',
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted     INT  DEFAULT 0
);

CREATE TABLE hib_document_permission
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    permission  VARCHAR(50) NOT NULL,
    granted_by  BIGINT,
    granted_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ,
    deleted     INT DEFAULT 0,
    CONSTRAINT uk_doc_user UNIQUE (document_id, user_id)
);

CREATE TABLE hib_webhook
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    event_type      VARCHAR(100) NOT NULL,
    target_url      VARCHAR(255) NOT NULL,
    enabled         INT    DEFAULT TRUE,
    secret          VARCHAR(255),
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT DEFAULT 0
);

CREATE TABLE hib_plugins (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             plugin_name        VARCHAR(255) NOT NULL,                      -- 插件名称
                             plugin_type        VARCHAR(100) NOT NULL,                      -- 插件类型（如：文本生成、图像识别等）
                             description        VARCHAR(1000),                              -- 插件描述（TEXT 替换为较长 VARCHAR）
                             version            VARCHAR(50) NOT NULL,                       -- 插件版本
                             webhook_url        VARCHAR(255),                               -- 插件 Webhook 地址
                             api_url            VARCHAR(255),                               -- 插件 API 地址
                             documentation_url  VARCHAR(255),                               -- 插件文档地址
                             author             VARCHAR(255),                               -- 插件作者
                             repository_url     VARCHAR(255),                               -- 源代码仓库地址
                             tags               VARCHAR(1000),                              -- 标签（JSON 在 H2 中以字符串形式存储）
                             last_validated_at  TIMESTAMP,                                  -- 最后验证时间
                             install_count      INT DEFAULT 0,                              -- 安装次数
                             download_count     INT DEFAULT 0,                              -- 下载次数
                             rating             DECIMAL(3,2),                               -- 评分
                             file_path          VARCHAR(500),                               -- 插件文件路径
                             status             VARCHAR(50) DEFAULT 'PENDING',              -- 插件状态
                             config_data        VARCHAR(1000),                              -- 插件配置数据（简化 JSON）
                             enabled            BOOLEAN DEFAULT TRUE,                       -- 是否启用
                             created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,        -- 创建时间
                             updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,        -- 更新时间
                             deleted            INT DEFAULT 0                               -- 逻辑删除标记（0未删除，1删除）
);
