apiVersion: v1
kind: ConfigMap
metadata:
  name: cowrite-config
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/cowrite
        username: cowrite
      redis:
        host: redis
        port: 6379
    logging:
      level:
        root: INFO 