/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedNumberCard: typeof import('./src/components/AnimatedNumberCard.vue')['default']
    AuditLogDialog: typeof import('./src/components/AuditLogDialog.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    AvatarGroup: typeof import('./src/components/AvatarGroup.vue')['default']
    CherryMarkdown: typeof import('./src/components/CherryMarkdown/index.vue')['default']
    ContributionGraph: typeof import('./src/components/ContributionGraph.vue')['default']
    CustomModal: typeof import('./src/components/CustomModal.vue')['default']
    DocumentActionBar: typeof import('./src/components/DocumentActionBar.vue')['default']
    DocumentPermissionDialog: typeof import('./src/components/DocumentPermissionDialog.vue')['default']
    DocumentShareDialog: typeof import('./src/components/DocumentShareDialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconRight: typeof import('~icons/ri/ght')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    LeftSidebar: typeof import('./src/components/LeftSidebar.vue')['default']
    Live2d: typeof import('./src/components/live2d/index.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    NestedOutlineEditor: typeof import('./src/components/NestedOutlineEditor.vue')['default']
    Notify: typeof import('./src/components/Notify.vue')['default']
    NotifyContainer: typeof import('./src/components/NotifyContainer.vue')['default']
    OnlineUsersPanel: typeof import('./src/components/OnlineUsersPanel.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PluginRunnerPanel: typeof import('./src/components/PluginRunnerPanel.vue')['default']
    RefreshPage: typeof import('./src/components/RefreshPage.vue')['default']
    RightSidebar: typeof import('./src/components/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    SharePasswordDialog: typeof import('./src/components/SharePasswordDialog.vue')['default']
    SiderMenu: typeof import('./src/components/SiderMenu.vue')['default']
    SnowEve: typeof import('./src/components/SnowEve.vue')['default']
    SystemToast: typeof import('./src/components/SystemToast.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    VegaLiteTest: typeof import('./src/components/VegaLiteTest.vue')['default']
    WChart: typeof import('./src/components/WChart.vue')['default']
  }
}
